
name = "Advanced Grappling"
mainprefix = "z"
prefix = "ag"

[files]
include = [
    "LICENSE",
    "mod.cpp",
    "README.md",
    "armaforces_NEW_MOD_SNAKE_x64.dll",
]

exclude = ["*.psd", "*.png", "*.tga"]

[properties]
author = "ArmaForces"

[version]
path = "addons/main/script_version.hpp"

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "730310357", # Advanced urban rapelling
    "623475643", # 3DEN Enhanced
    "1779063631", # Zeus Enhanced
]
parameters = [
    "-noPause",
    "-noPauseAudio",
]
mission = "test.VR"

[hemtt.launch.ace]
extends = "default"
workshop = [
    "463939057", # ACE
]

[hemtt.launch.windowed]
extends = "ace"
parameters = [
    "-window",
]
